config/routes.rb
GlassVision::Application.routes.draw do
  resources :emails
  get '/signup', to: 'users#new', as: :signup
  get '/login', to: 'session#new', as: :login
  get '/logout', to: 'session#destroy', as: :logout
  get '/activate/:id', to: 'accounts#show', as: :activate
  get '/forgot_password', to: 'passwords#new', as: :forgot_password
  get '/reset_password/:id', to: 'passwords#edit', as: :reset_password
  get '/change_password', to: 'accounts#edit', as: :change_password
  get '/set_lang', to: 'home#set_lang'
  get '/company/list', to: 'company#list'
  get '/translation/list', to: 'translation#list'
  
  resources :users do
    post :enable
    post :disable
    resource :account
    resources :roles
  end
  
  resources :audits, only: :index
  resources :product_colors
  resources :shapes
  resources :openings
  post '/customers/show_by_name', to: 'customers#show_by_name'
  resources :customers
  resources :options
  resources :option_categories do
    member do
      get :edit_options
      put :update_options
    end
  end
  resources :pricing_methods
  resources :roles
  resources :doors do
    collection do
      get 'configure_panels'
      get 'configure_panel_dimensions'
      get 'configure_glass_families'
      get 'configure_glasses'
      get 'configure_openings'
    end
  end
  resources :door_frames
  resources :door_combinations
  resources :frame_profiles
  resources :slab_materials
  resources :door_openings
  resources :door_glass_families do
    resources :door_glasses
  end
  resources :door_panel_families do
    resources :door_panels do
      resources :door_panel_dimensions
    end
  end
  resources :door_borings
  resources :door_sections
  resources :manual_lines

  resource :session, controller: :session
  resource :passwords
  resources :quotations, controller: :quotation do
    get :autocomplete_customer_name, on: :collection
    collection do
      post :search
    end
    post :copy
    # get :print
    get :print_invoice
    get :print_calculations
    get :print_manifest
  end

  get '/quotation/print/:id', to: 'quotation#print'
  get '/quotation_line/add', to: 'quotation_line#add'
  get '/option_quotation/add', to: 'option_quotation#add'

  resources :series do
    get :edit_prices
  end
  root to: 'home#index'

  # match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/models/door_glass_family.rb
# == Schema Information
#
# Table name: door_glass_families
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class DoorGlassFamily < ApplicationRecord
  translates :name
  accepts_nested_attributes_for :translations
  has_many :door_glasses, dependent: :destroy
end

app/controllers/door_glass_families_controller.rb
class DoorGlassFamiliesController < ApplicationController
  def index
    @door_glass_families = DoorGlassFamily.all(order: :name)
  end

  def new
    @door_glass_family = DoorGlassFamily.new
  end

  def edit
    @door_glass_family = DoorGlassFamily.find(params[:id])
  end

  def create
    @door_glass_family = DoorGlassFamily.new(params[:door_glass_family])
    if @door_glass_family.save
      flash[:notice] = "#{trn_geth('LABEL_DOOR_GLASS_FAMILY')} #{trn_get('MSG_SUCCESSFULLY_CREATED_F')}"
      redirect_to door_glass_families_path
    else
      render action: 'new'
    end
  end

  def update
    @door_glass_family = DoorGlassFamily.find(params[:id])
    if @door_glass_family.update(params[:door_glass_family])
      flash[:notice] = "#{trn_geth('LABEL_DOOR_GLASS_FAMILY')} #{trn_get('MSG_SUCCESSFULLY_MODIFIED_F')}"
      redirect_to door_glass_families_path
    else
      render action: 'edit'
    end
  end

  def destroy
    DoorGlassFamily.find(params[:id]).destroy
    flash[:notice] = "#{trn_geth('LABEL_DOOR_GLASS_FAMILY')} #{trn_get('MSG_SUCCESSFULLY_DELETED_F')}"
    redirect_to door_glass_families_path
  end
end

app/views/door_glass_families/_form.html.erb
<%= error_messages_for 'door_glass_family' %>

<table>
  <%= gv_fields_for(f, :name, 'LABEL_NAME', :size => 30) %>
</table>

app/views/door_glass_families/edit.html.erb
<h2><%= trn_get('TITLE_DOOR_GLASS_FAMILY_EDIT') %></h2>

<%= form_for @door_glass_family do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag trn_geth('BUTTON_EDIT') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_glass_families_path %> |
<%= link_to trn_geth('BUTTON_DELETE'), door_glass_family_path(@door_glass_family), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>

app/views/door_glass_families/index.html.erb
<h2><%= trn_geth('TITLE_DOOR_GLASS_FAMILY_LIST') %></h2>

<%= link_to trn_geth('BUTTON_ADD'), new_door_glass_family_path %>
<table cellspacing="0">
  <tr class="header">
    <th><%= trn_geth('HEADER_NAME') %></th>
    <th></th>
  </tr>
<% for door_glass_family in @door_glass_families %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= door_glass_family.name %></td>
    <td>
      <%= link_to trn_geth('BUTTON_GLASSES'), door_glass_family_door_glasses_path(door_glass_family) %> |
      <%= link_to trn_geth('BUTTON_EDIT'), edit_door_glass_family_path(door_glass_family) %> |
      <%= link_to trn_geth('BUTTON_DELETE'), door_glass_family_path(door_glass_family), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/door_glass_families/new.html.erb
<h2><%= trn_get('TITLE_DOOR_GLASS_FAMILY_ADD') %></h2>

<%= form_for @door_glass_family do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag trn_geth('BUTTON_ADD') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_glass_families_path %>