config/routes.rb
GlassVision::Application.routes.draw do
  resources :emails
  get '/signup', to: 'users#new', as: :signup
  get '/login', to: 'session#new', as: :login
  get '/logout', to: 'session#destroy', as: :logout
  get '/activate/:id', to: 'accounts#show', as: :activate
  get '/forgot_password', to: 'passwords#new', as: :forgot_password
  get '/reset_password/:id', to: 'passwords#edit', as: :reset_password
  get '/change_password', to: 'accounts#edit', as: :change_password
  get '/set_lang', to: 'home#set_lang'
  get '/company/list', to: 'company#list'
  get '/translation/list', to: 'translation#list'
  
  resources :users do
    post :enable
    post :disable
    resource :account
    resources :roles
  end
  
  resources :audits, only: :index
  resources :product_colors
  resources :shapes
  resources :openings
  post '/customers/show_by_name', to: 'customers#show_by_name'
  resources :customers
  resources :options
  resources :option_categories do
    member do
      get :edit_options
      put :update_options
    end
  end
  resources :pricing_methods
  resources :roles
  resources :doors do
    collection do
      get 'configure_panels'
      get 'configure_panel_dimensions'
      get 'configure_glass_families'
      get 'configure_glasses'
      get 'configure_openings'
    end
  end
  resources :door_frames
  resources :door_combinations
  resources :frame_profiles
  resources :slab_materials
  resources :door_openings
  resources :door_glass_families do
    resources :door_glasses
  end
  resources :door_panel_families do
    resources :door_panels do
      resources :door_panel_dimensions
    end
  end
  resources :door_borings
  resources :door_sections
  resources :manual_lines

  resource :session, controller: :session
  resource :passwords
  resources :quotations, controller: :quotation do
    get :autocomplete_customer_name, on: :collection
    collection do
      post :search
    end
    post :copy
    # get :print
    get :print_invoice
    get :print_calculations
    get :print_manifest
  end

  get '/quotation/print/:id', to: 'quotation#print'
  get '/quotation_line/add', to: 'quotation_line#add'
  get '/option_quotation/add', to: 'option_quotation#add'

  resources :series do
    get :edit_prices
  end
  root to: 'home#index'

  # match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout 'application'
  before_action :login_required, only: :destroy
  before_action :not_logged_in_required, only: %i[new create]

  # for some reason, setting language after login failure routes to show
  def show
    redirect_to login_path
  end

  # render new.rhtml
  def new; end

  def create
    password_authentication(params[:login], params[:password])
  end

  def destroy
    user = current_user
    current_user.forget_me if logged_in?
    cookies.delete :auth_token
    reset_session
    flash[:notice] = trn_get('LOGGED_OUT_FLASH')
    Audit.write_audit(user, 'logout', 'Success')
    redirect_to login_path
  end

  protected

  # Updated 2/20/08
  def password_authentication(login, password)
    user = User.authenticate(login, password)
    if user.nil?
      failed_login('LOGIN_FAILED_FLASH')
    elsif user.activated_at.blank?
      Audit.write_audit(user, 'login', 'Failure', 'User is not activated')
      failed_login('LOGIN_ACCT_NOT_ACTIVE_FLASH')
    elsif user.enabled == false
      Audit.write_audit(user, 'login', 'Failure', 'User is disabled')
      failed_login('LOGIN_ACCT_DISABLED_FLASH')
    else
      self.current_user = user
      Audit.write_audit(user, 'login', 'Success', 'from username/password')
      successful_login
    end
  end

  private

  def failed_login(message)
    flash.now[:error] = trn_get(message)
    render action: 'new'
  end

  def successful_login
    if params[:remember_me] == '1'
      current_user.remember_me
      cookies[:auth_token] =
        { value: current_user.remember_token, expires: current_user.remember_token_expires_at }
    end
    flash[:notice] = trn_get('LOGIN_SUCCESSFUL_FLASH')
    return_to = session[:return_to]
    if return_to.nil?
      redirect_to user_path(current_user)
    else
      redirect_to return_to
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<div style="text-align:center;">
  <div id="login_frame">
    <div id="login_logo">
      <%= image_tag 'logos/glass-vision.png' %>
    </div>
  <h2 class="clearfix"><%= trn_get('LOGIN_WELCOME_LABEL') %><br/></h2>
  <p style="clear:both;line-height:5px;" >&nbsp;</p> 
  <fieldset>
    <legend> <%= trn_geth('PLEASE_LOGIN_LABEL') %> </legend>
    <%= form_tag session_path, data: { turbo: false } do %>
    <p><label for="login"><%= trn_geth('LOGIN_LABEL') %></label><br/>
    <%= text_field_tag 'login' %></p>
     
    <p><label for="password"><%= trn_geth('PASSWORD_LABEL') %></label><br />
    <%= password_field_tag 'password' %><br />
    <%= link_to trn_geth('FORGOT_PASSWORD_LABEL'), forgot_password_path %></p>
     
    <p><label for="remember_me"><%= trn_geth('REMEMBER_ME_LABEL') %>:</label>
    <%= check_box_tag 'remember_me' %></p>
     
    <p style="line-height:1.5em;"><%= submit_tag trn_geth('LOGIN_LABEL') %><br /><%= trn_geth('LOGIN_SIGNUP_PROMPT') %> <%= link_to trn_get('SIGNUP_LABEL'), new_user_path %></p>
  <% end %>
  </fieldset>
  </div>
</div>