config/routes.rb
GlassVision::Application.routes.draw do
  resources :emails
  get '/signup', to: 'users#new', as: :signup
  get '/login', to: 'session#new', as: :login
  get '/logout', to: 'session#destroy', as: :logout
  get '/activate/:id', to: 'accounts#show', as: :activate
  get '/forgot_password', to: 'passwords#new', as: :forgot_password
  get '/reset_password/:id', to: 'passwords#edit', as: :reset_password
  get '/change_password', to: 'accounts#edit', as: :change_password
  get '/set_lang', to: 'home#set_lang'
  get '/company/list', to: 'company#list'
  get '/translation/list', to: 'translation#list'
  
  resources :users do
    post :enable
    post :disable
    resource :account
    resources :roles
  end
  
  resources :audits, only: :index
  resources :product_colors
  resources :shapes
  resources :openings
  post '/customers/show_by_name', to: 'customers#show_by_name'
  resources :customers
  resources :options
  resources :option_categories do
    member do
      get :edit_options
      put :update_options
    end
  end
  resources :pricing_methods
  resources :roles
  resources :doors do
    collection do
      get 'configure_panels'
      get 'configure_panel_dimensions'
      get 'configure_glass_families'
      get 'configure_glasses'
      get 'configure_openings'
    end
  end
  resources :door_frames
  resources :door_combinations
  resources :frame_profiles
  resources :slab_materials
  resources :door_openings
  resources :door_glass_families do
    resources :door_glasses
  end
  resources :door_panel_families do
    resources :door_panels do
      resources :door_panel_dimensions
    end
  end
  resources :door_borings
  resources :door_sections
  resources :manual_lines

  resource :session, controller: :session
  resource :passwords
  resources :quotations, controller: :quotation do
    get :autocomplete_customer_name, on: :collection
    collection do
      post :search
    end
    post :copy
    # get :print
    get :print_invoice
    get :print_calculations
    get :print_manifest
  end

  get '/quotation/print/:id', to: 'quotation#print'
  get '/quotation_line/add', to: 'quotation_line#add'
  get '/option_quotation/add', to: 'option_quotation#add'

  resources :series do
    get :edit_prices
  end
  root to: 'home#index'

  # match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  has_many :quotation_lines, dependent: :destroy
  has_many :door_lines, dependent: :destroy
  has_many :options_quotations, dependent: :destroy
  has_many :manual_lines, dependent: :destroy
  belongs_to :user
  belongs_to :company

  validates :project_name, presence: true
  validates :markup, numericality: { allow_nil: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 60 }
  validates :deposit, numericality: { allow_nil: true, greater_than_or_equal_to: 0 }

  after_initialize :set_tax_rates

  def set_tax_rates
    return unless new_record? && !changed?

    self.taxes ||= 5.0
    self.taxes_pst ||= 9.5
  end

  def use_billing_address?
    return false if customer_address.nil? || delivery_address.nil?

    customer_address == delivery_address
  end

  def calculate_taxes(total)
    total * self.taxes / 100.0
  end

  def calculate_pst(total)
    if self.taxes_pst.blank?
      0.0
    else
      total * self.taxes_pst / 100.0
    end
  end

  # given a source quotation, copy to new with derivative slug
  def self.copy(orig_quotation)
    quotation = orig_quotation.deep_clone include: [:manual_lines, :options_quotations,
                                                    { quotation_lines: %i[quotation_lines_openings options_quotation_lines section_heights section_widths] },
                                                    { door_lines: %i[door_line_sections door_line_options] }]
    quotation.slug = quotation.generate_new_slug(orig_quotation.slug)
    quotation.created_at = nil # ensure the new quotation has the current date.
    quotation.save!
    quotation
  end

  def regenerate_previews(base_url)
    quotation_lines.each(&:create_image)
    door_lines.each do |line|
      line.create_image(base_url)
    end
  end

  def generate_new_slug(slug)
    last = 1

    base_slug = Quotation.get_base_slug(slug)
    existing_slugs = Quotation.connection.select_all("select slug from quotations where slug like '#{base_slug}%'")
    existing_slugs = existing_slugs.pluck('slug')
    last = existing_slugs.collect { |s| s[((s.rindex('-') || -1) + 1)..].to_i }.max + 1 unless existing_slugs.empty?

    base_slug + last.to_s
  end

  def has_manual_lines?
    manual_lines.length.positive?
  end

  def has_options?
    options_quotations.length.positive?
  end

  def self.get_base_slug(slug)
    # we have to handle the following cases:
    # 1) quotation that's never been copied and slug is original id (eg 900), no dashes at all
    # 2) quotation with new format slug (eg 13-0101), never copied
    # 3) quotation with id + copy (eg 900-2)
    # 4) quotation with new format slug that's been copied (13-01010-1)

    # cases 2 and 4 can be handled the same way, as we just want the root slug.
    base_slug = slug.slice(/\d+-\d{4}-/) # case #4
    base_slug ||= slug.slice(/\d+-/) unless slug.match(/^\d+(-\d{4})*$/) # case 3
    base_slug ||= "#{slug}-"
  end
end

app/controllers/quotation_controller.rb
class QuotationController < ApplicationController
  include Retryable

  autocomplete :customer, :name, full: true, extra_data: %i[address phone fax email]

  before_action :find_quotation, only: %i[show print print_invoice print_manifest print_calculations]
  # sortable_attributes  :updated_at, :slug, :description, :user_id, :consultant

  SEARCH_FIELDS = %w[search_description search_slug].freeze

  def index
    searcher = SearchConditions.new(session, SEARCH_FIELDS, params)

    conditions = { user_id: @current_user.id } unless @current_user.admin?
    search_conditions = searcher.conditions { |x, v, searcher| search_condition_for(x, v, searcher) }

    @quotations = Quotation.includes(:user).where(conditions).where(search_conditions).paginate(page: params[:page], per_page: 25) # .order(sort_order || 'updated_at DESC')
  end

  def show
    return unless @quotation.user_id != @current_user.id && !@current_user.admin?

    flash[:notice] = trn_geth('PERMISSION_DENIED')
    redirect_to action: 'index'
  end

  def new
    @quotation = Quotation.new
    @quotation.discount = @current_user.discount
    @users = User.enabled
  end

  def edit
    @quotation = Quotation.find_by(slug: params[:id])
    @users = User.enabled
  end

  def create
    set_taxes_if_not_present

    @quotation = Quotation.new(quote_params[:quotation])
    @quotation.user_id = @current_user.id
    customer_msg = ''
    if Customer.create_from_quotation_if_new(@quotation)
      customer_msg = "#{trn_geth('LABEL_CUSTOMER')} #{trn_get('MSG_SUCCESSFULLY_CREATED_F')}"
    end
    if @quotation.save
      if @quotation.slug.blank?
        @quotation.slug = InvoiceNumber.get_next_invoice_number
        @quotation.save
      end
      customer_msg += '<br />' if customer_msg.present?
      customer_msg += "#{trn_geth('LABEL_QUOTATION')} #{trn_get('MSG_SUCCESSFULLY_CREATED_F')}"
      flash[notice] = customer_msg.html_safe
      redirect_to action: 'show', id: @quotation.slug
    else
      render action: 'new'
    end
  end

  def update
    set_taxes_if_not_present

    quotation = Quotation.find(params[:id])

    if quotation.update(quote_params[:quotation])
      flash[:notice] = "#{trn_geth('LABEL_QUOTATION')} #{trn_get('MSG_SUCCESSFULLY_MODIFIED_F')}"
      redirect_to action: 'show', id: quotation.slug
    else
      render action: 'edit'
    end
  end

  def destroy
    Quotation.find(params[:id]).destroy
    flash[:notice] = "#{trn_geth('LABEL_QUOTATION')} #{trn_get('MSG_SUCCESSFULLY_DELETED_F')}"
    redirect_to action: 'index'
  end

  def print
    retryable(tries: 5, on: RuntimeError) do
      render pdf: "#{@quotation.slug}-#{@quotation.project_name}", layout: 'printer', disposition: 'inline',
             temp_path: Rails.root.join('tmp'), show_as_html: params[:debug].present?, header: { right: '[page] of [topage]' }
    end
  end

  def print_invoice
    retryable(tries: 5, on: RuntimeError) do
      render pdf: "#{@quotation.slug}-#{@quotation.project_name}-#{trn_get('PRINT_INVOICE_TITLE')}",
             layout: 'printer', show_as_html: params[:debug].present?, header: { right: '[page] of [topage]' }
    end
  end

  def print_manifest
    retryable(tries: 5, on: RuntimeError) do
      render pdf: "#{@quotation.slug}-#{@quotation.project_name}-#{trn_get('BUTTON_PRINT_MANIFEST')}",
             layout: 'printer', show_as_html: params[:debug].present?, header: { right: '[page] of [topage]' }
    end
  end

  def print_calculations
    if current_user.has_role?('administrator')
      retryable(tries: 5, on: RuntimeError) do
        render pdf: "#{@quotation.slug}-#{@quotation.project_name}-#{trn_get('BUTTON_PRINT_CALCULATIONS')}",
               layout: 'printer', show_as_html: params[:debug].present?, header: { right: '[page] of [topage]' }
      end
    else
      redirect_to action: 'index'
    end
  end

  def copy
    #    return unless request.xhr?
    @orig_quotation = Quotation.includes(quotation_lines: [:serie, :shape, { quotation_lines_openings: :opening },
                                                           { options_quotation_lines: :option }]).find_by(slug: params[:quotation_id])
    if @orig_quotation.user_id != @current_user.id && !@current_user.admin?
      flash[notice] = trn_get('PERMISSION_DENIED')
      redirect_to action: 'index'
    end
    @quotation = Quotation.copy(@orig_quotation)
    @quotation.save!
    application_url = "#{request.protocol}#{request.host_with_port}"
    @quotation.regenerate_previews(application_url)
    flash[:notice] = "#{trn_geth('LABEL_QUOTATION')} #{trn_get('MSG_SUCCESSFULLY_CREATED_F')}"
    redirect_to quotation_path(@quotation.slug)
  end

  def search
    searcher = SearchConditions.new(session, SEARCH_FIELDS, params)

    conditions = { user_id: @current_user.id } unless @current_user.admin?
    search_conditions = searcher.conditions { |x, v, searcher| search_condition_for(x, v, searcher) }

    @quotations = Quotation.includes(:user).where(conditions).where(search_conditions).paginate(page: params[:page],
                                                                                                per_page: 25).order('updated_at DESC')

    render :index
  end

  protected

  def search_condition_for(field, value, searcher)
    return nil if value.blank?

    case field.gsub(/search_/, '')
    when 'slug'
      "slug #{searcher.send(:match_anywhere, value)}"
    when 'description'
      "customer_name#{searcher.send(:match_anywhere, value)}"
    end
  end

  def find_quotation
    @quotation = Quotation.includes(quotation_lines: [:serie, :shape, { quotation_lines_openings: :opening },
                                                      { options_quotation_lines: :option }]).find_by(slug: params[:id])
  end

  def set_taxes_if_not_present
    return unless params[:quotation]

    params[:quotation]['taxes']     = 0.0 if params[:quotation]['taxes'].blank?
    params[:quotation]['taxes_pst'] = 0.0 if params[:quotation]['taxes_pst'].blank?
  end

  # override default behavior of autocomplete
  alias_method :get_autocomplete_items_original, :get_autocomplete_items
  def get_autocomplete_items(parameters)
    if @current_user.admin?
      get_autocomplete_items_original(parameters)
    else
      get_autocomplete_items_original(parameters).where(user_id: @current_user.id)
    end
  end

  private

  def quote_params
    params.permit(
      customer: %i[name address phone fax email],
      quotation: %i[description comments project_name customer_name customer_address delivery_address
                    customer_phone customer_fax customer_email contact cell_phone notes transport discount markup taxes taxes_pst deposit ready_to_sign company_id consultant]
    ).to_h.symbolize_keys
  end
end

app/views/quotation/_door_line.html.erb
  <tr valign="top" class="quotation-line">
  <tr valign="top" class="quotation-line">
    <td width="1%" style="border-bottom: 2px dotted #808080;"><%= image_tag "/system/images/doors/preview_#{door.id}.png" %></td>
    <td style="border-bottom: 2px dotted #808080;">

      <table>
        <tr>
          <td><%= trn_geth('HEADER_DOOR_COMBINATION') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.door_combination.name %></td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_FRAME_PROFILE') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.frame_profile.name %></td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_SLAB_MATERIAL') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.slab_material.name %></td>
        </tr>
        <% if !door.interior_color.blank? || !door.standard_interior_color.blank? %>
          <tr>
            <td><%= trn_get('LABEL_INTERIOR_COLOR')%></td>
            <td><%= h door.interior_color.blank? ? door.standard_interior_color.name : door.interior_color + trn_get("LABEL_CUSTOM") %></td>
          </tr>
        <% end %>
        <% if !door.exterior_color.blank?  || !door.standard_exterior_color.blank?%>
          <tr>
            <td><%= trn_get('LABEL_EXTERIOR_COLOR')%></td>
            <td><%= h door.exterior_color.blank? ? door.standard_exterior_color.name : door.exterior_color + trn_get("LABEL_CUSTOM") %> </td>
          </tr>
        <% end %>
        <tr>
          <td><%= trn_geth('HEADER_DOOR_OPENING') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.door_opening.name %></td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_DOOR_BORING') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.door_boring.name %></td>
        </tr>
        <% door.door_line_sections.each_with_index do |section, index| %>
        <tr>
          <td valign="top"><%= trn_geth('HEADER_DOOR_SECTION') %> <%= index + 1 %><%= trn_geth('LABEL_SEMICOLON') %></td>
          <td>
            <%= trn_geth('HEADER_DOOR_SECTION') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_section.name %><br/>
            <% if section.door_panel %>
              <%= trn_geth('HEADER_DOOR_PANEL') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_panel.name %><br/>
            <% end %>
            <% if section.door_glass %>
              <%= trn_geth('HEADER_DOOR_GLASS') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_glass.door_glass_family.name %> / <%= section.door_glass.name %><br/>
            <% end %>
            <%= trn_geth('HEADER_DOOR_PANEL_HEIGHT') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_panel_dimension.try(:height) %>" x
            <%= trn_geth('HEADER_DOOR_PANEL_WIDTH') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_panel_dimension.try(:width) %>"<br/>
          </td>
        </tr>
        <% end %>
        <% if door.door_line_options.length > 0 %>
        <tr>
          <td valign="top"><%= trn_geth('HEADER_OPTIONS') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td>
            <% for option in door.door_line_options %>
              <%= option.option.description %>
              <% if option.quantity != 1 %>
                x <%= option.quantity %>
              <% end %>
              <br/>
            <% end %>
          </td>
        </tr>
        <% end %>
        <tr>
          <td><%= trn_geth('HEADER_UNIT_PRICE') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td class="price-override-handle"
              data-uri='<%= url_for(:controller => 'doors', :action => 'update_line_price', :id => door.id ) %>'
              data-full-price='<%= door.price %>' data-discount='<%= quotation.discount %>'
              data-markup='<%= quotation.markup %>'
              data-current-price='<%= door.price %>' data-original-price='<%= door.original_price %>'
              style='cursor:pointer'>
            <% unit_price_style = current_user.has_role?('administrator') && door.has_price_override? ? 'font-weight:bold;font-style:italic;' : '' %>
            <%= content_tag 'span', :style => unit_price_style do -%>
              <%= number_to_currency(door_price) %>
            <% end -%>
          </td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_QUANTITY') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.quantity %></td>
        </tr>
      </table>

    </td>
    <td align="right" style="border-bottom: 2px dotted #808080;"><%= number_to_currency(door.quantity * door.price) %></td>
    <td nowrap="nowrap" style="border-bottom: 2px dotted #808080;">
      <%= link_to trn_geth('BUTTON_EDIT'), edit_door_path(door) %> |
      <%= link_to trn_geth('BUTTON_DELETE'), door_path(door), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>
    </td>
  </tr>

app/views/quotation/_form.html.erb
<%= flash[:error] %>

<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DESCRIPTION') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'description', :size => 50%></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_COMMENTS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area 'quotation', 'comments', :cols => '39', :rows => '7' %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_PROJECT_NAME') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'project_name', :size => 50 %><strong> *</strong></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_NAME') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td>
      <%#= text_field :quotation, :customer_name, :size => 50  %>
      <%= autocomplete_field :quotation, :customer_name, autocomplete_customer_name_quotations_path, :size => 50,
                             :update_elements  => {
                                     :address   => '#customer_address',
                                     :phone => '#customer_phone',
                                     :email => '#customer_email',
                                     :fax => '#customer_fax'
                             } %>
    </td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_NAME_PICK') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= select('customer', 'name', Customer.all.collect(&:name)) %>
    </td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_ADDRESS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area 'quotation', 'customer_address', :cols => '39', :rows => '5', :id => 'customer_address'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DELIVERY_ADDRESS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area 'quotation', 'delivery_address', :cols => '39', :rows => '5', :id => 'delivery_address'  %>
      <br />
      <label class="clickable">
        <%= check_box_tag 'use_billing_address', @quotation.use_billing_address? %><%= trn_get('LABEL_SAME_DELIVERY_ADDRESS') %>
      </label>
    </td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_PHONE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'customer_phone', :size => 50, :id => 'customer_phone'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_FAX') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'customer_fax', :size => 50, :id => 'customer_fax'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_EMAIL') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'customer_email', :size => 50, :id => 'customer_email'  %></td>
  </tr>

  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_QUOTATION_CONTACT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'contact', :size => 50, :id => 'contact'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_QUOTATION_CELLPHONE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'cell_phone', :size => 50, :id => 'cell_phone' %></td>
  </tr>


  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_NOTES') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area 'quotation', 'notes', :cols => '39', :rows => '5' %></td>
  </tr>
</table>
<hr/>
<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_TRANSPORT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td>$<%= text_field 'quotation', 'transport', :size => 10, :style => 'text-align: right;' %></td>
  </tr>
  <% if current_user.has_role?('administrator')%>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DISCOUNT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td>$<%= text_field 'quotation', 'discount', :size => 10, :style => 'text-align: right;' %></td>
  </tr>
  <% else %>
    <%= hidden_field 'quotation', 'discount' %>
  <% end %>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_MARKUP') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'markup', :size => 10, :style => 'text-align: right;' %>%</td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_get('LABEL_TAXES') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'taxes', :size => 10, :style => 'text-align: right;' %>%</td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_get('LABEL_PST_RATE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'taxes_pst', :size => 10, :style => 'text-align: right;' %>%</td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DEPOSIT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td>$<%= text_field 'quotation', 'deposit', :size => 10, :style => 'text-align: right;' %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_QUOTE_READY_TO_SIGN') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= check_box 'quotation', 'ready_to_sign' %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_COMPANY') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= select 'quotation', 'company_id', @current_user.active_companies.map { |c| [c.name, c.id] } %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CONSULTANT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'consultant',  :size => 50  %></td>
  </tr>
<% if @current_user.admin? %>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_ASSIGNED_TO') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= select 'quotation', 'user_id',  User.all.map {|u| [u.login, u.id]}  %></td>
  </tr>
<% end %>
</table>

<% content_for :extra_javascript do %>
    $("#use_billing_address").change(function() {
        if(this.checked) {
            $('#delivery_address').val($('#customer_address').val());
        } else {
          $('#delivery_address').val('');
        }
    });

    $('#customer_name').change(function () {
        $.ajax({
        url: "< url_for(:controller => 'customer', :action => 'show_by_name') >",
        dataType: 'script',
        data: { customer_name : $('#customer_name').val()}
        }).done(function (data) {
            if ($("#use_billing_address").is(':checked')) {
                $('#delivery_address').val($('#customer_address').val());
            }
        });
    });

    $('#quotation_customer_name').bind('railsAutocomplete.select', function(event, data){
        if ($("#use_billing_address").is(':checked')) {
            $('#delivery_address').val($('#customer_address').val());
        }
    });

<% end %>

app/views/quotation/_print_header.html.erb
<table cellpadding="5" width="100%">
  <tr valign="top" width="1%">
    <td rowspan="2">
      <%= wicked_pdf_dynamic_image_tag @quotation.company.logo.url if @quotation.company.logo.present? %>
    </td>
    <td rowspan="2" width="1%" nowrap="nowrap">
      <strong><%= @quotation.company.name %></strong><br/>
      <%= @quotation.company.address.gsub(/\n/, '<br/>').html_safe %><br/>
      <%= trn_geth('PRINT_LABEL_PHONE') %><%= trn_geth('LABEL_SEMICOLON') %><%= @quotation.company.phone %><br/>
      <%= trn_geth('PRINT_LABEL_FAX') %><%= trn_geth('LABEL_SEMICOLON') %><%= @quotation.company.fax %>
    </td>
    <td width="98%" align="right">
      <h2>
        #<%= @quotation.slug %>
        <%= @quotation.project_name %>
      </h2>
      <%= gv_humanize_time @quotation.updated_at %>
      <br/>
      <%= @quotation.consultant%>
    </td>
  </tr>
  <tr>
    <td>
      <%= @quotation.description %>
    </td>
  </tr>
</table>

app/views/quotation/index.html.erb
<h2><%= trn_geth('TITLE_QUOTATION_LIST') %></h2>

<%= link_to trn_geth('BUTTON_ADD'), new_quotation_path %>

<%= form_tag search_quotations_path, remote: true , id: 'quotation-search-form' do %>
  <%= submit_tag 'Search', style: 'position:absolute;bottom:-20px;left:-20px;z-index:-1;' %>

  <div id="results">
    <%= render :partial => 'quotation_list'%>
  </div>
<% end %>

<% content_for :extra_javascript do %>
    // :update => "results"
<% end %>