config/routes.rb
GlassVision::Application.routes.draw do
  resources :emails
  get '/signup', to: 'users#new', as: :signup
  get '/login', to: 'session#new', as: :login
  get '/logout', to: 'session#destroy', as: :logout
  get '/activate/:id', to: 'accounts#show', as: :activate
  get '/forgot_password', to: 'passwords#new', as: :forgot_password
  get '/reset_password/:id', to: 'passwords#edit', as: :reset_password
  get '/change_password', to: 'accounts#edit', as: :change_password
  get '/set_lang', to: 'home#set_lang'
  get '/company/list', to: 'company#list'
  get '/translation/list', to: 'translation#list'
  
  resources :users do
    post :enable
    post :disable
    resource :account
    resources :roles
  end
  
  resources :audits, only: :index
  resources :product_colors
  resources :shapes
  resources :openings
  post '/customers/show_by_name', to: 'customers#show_by_name'
  resources :customers
  resources :options
  resources :option_categories do
    member do
      get :edit_options
      put :update_options
    end
  end
  resources :pricing_methods
  resources :roles
  resources :doors do
    collection do
      get 'configure_panels'
      get 'configure_panel_dimensions'
      get 'configure_glass_families'
      get 'configure_glasses'
      get 'configure_openings'
    end
  end
  resources :door_frames
  resources :door_combinations
  resources :frame_profiles
  resources :slab_materials
  resources :door_openings
  resources :door_glass_families do
    resources :door_glasses
  end
  resources :door_panel_families do
    resources :door_panels do
      resources :door_panel_dimensions
    end
  end
  resources :door_borings
  resources :door_sections
  resources :manual_lines

  resource :session, controller: :session
  resource :passwords
  resources :quotations, controller: :quotation do
    get :autocomplete_customer_name, on: :collection
    collection do
      post :search
    end
    post :copy
    # get :print
    get :print_invoice
    get :print_calculations
    get :print_manifest
  end

  get '/quotation/print/:id', to: 'quotation#print'
  get '/quotation_line/add', to: 'quotation_line#add'
  get '/option_quotation/add', to: 'option_quotation#add'

  resources :series do
    get :edit_prices
  end
  root to: 'home#index'

  # match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/models/door_panel.rb
class DoorPanel < ApplicationRecord
  include Priceable
  translates :name
  accepts_nested_attributes_for :translations

  has_and_belongs_to_many :door_glasses
  has_and_belongs_to_many :door_sections
  belongs_to :door_panel_family
  has_many :door_panel_dimensions, -> { order(height: :asc, width: :asc) } # double check this
end

app/controllers/door_panels_controller.rb
class DoorPanelsController < ApplicationController
  def index
    @door_panel_family = DoorPanelFamily.find(params[:door_panel_family_id])
  end

  def new
    @door_panel_family = DoorPanelFamily.find(params[:door_panel_family_id])
    @door_panel = @door_panel_family.door_panels.new
    @door_sections = DoorSection.all(order: :name)
  end

  def edit
    @door_panel_family = DoorPanelFamily.find(params[:door_panel_family_id])
    @door_panel = DoorPanel.find(params[:id])
    @door_sections = DoorSection.all(order: :name)
  end

  def create
    @door_panel_family = DoorPanelFamily.find(params[:door_panel_family_id])
    @door_panel = @door_panel_family.door_panels.new(params[:door_panel])
    if @door_panel.save
      flash[:notice] = "#{trn_geth('LABEL_DOOR_PANEL')} #{trn_get('MSG_SUCCESSFULLY_CREATED_M')}"
      redirect_to door_panel_family_door_panels_path(@door_panel_family)
    else
      render action: 'new'
    end
  end

  def update
    @door_panel_family = DoorPanelFamily.find(params[:door_panel_family_id])
    @door_panel = DoorPanel.find(params[:id])
    if @door_panel.update(params[:door_panel])
      flash[:notice] = "#{trn_geth('LABEL_DOOR_PANEL')} #{trn_get('MSG_SUCCESSFULLY_MODIFIED_M')}"
      redirect_to door_panel_family_door_panels_path(@door_panel_family)
    else
      render action: 'edit'
    end
  end

  def destroy
    @door_panel_family = DoorPanelFamily.find(params[:door_panel_family_id])
    DoorPanel.find(params[:id]).destroy
    flash[:notice] = "#{trn_geth('LABEL_DOOR_PANEL')} #{trn_get('MSG_SUCCESSFULLY_DELETED_M')}"
    redirect_to door_panel_family_door_panels_path(@door_panel_family)
  end
end

app/views/door_panels/_form.html.erb
<%= error_messages_for 'door_panel' %>

<table>
  <%= gv_fields_for(f, :name, 'LABEL_NAME', :size => 30) %>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_PREVIEW_IMAGE_NAME') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= f.text_field 'preview_image_name', :size => 20 %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_SELECT_DOOR_SECTIONS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td>
      <% @door_sections.each do |door_section| %>
        <%= check_box_tag 'door_panel[door_section_ids][]', door_section.id, @door_panel.door_sections.exists?(:id => door_section.id) %> <%= door_section.name %><br/>
      <% end %>
    </td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_GAP') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= f.select 'gap', %w{slab l lp slf}.collect { |g| [g.upcase, g] } %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_PRICE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= f.text_field 'price', :size => 20 %></td>
  </tr>
</table>

app/views/door_panels/edit.html.erb
<h2><%= trn_get('TITLE_DOOR_PANEL_EDIT') %></h2>

<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DOOR_PANEL_FAMILY') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= @door_panel_family.name %></td>
  </tr>
</table>
<br/>

<%= form_for [@door_panel_family, @door_panel], :method => :put do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag trn_geth('BUTTON_EDIT') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_panel_family_door_panels_path(@door_panel_family) %> |
<%= link_to trn_geth('BUTTON_DELETE'), door_panel_family_door_panel_path(@door_panel_family, @door_panel), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>

app/views/door_panels/index.html.erb
<h2><%= trn_geth('TITLE_DOOR_PANEL_LIST') %></h2>

<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DOOR_PANEL_FAMILY') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= @door_panel_family.name %></td>
  </tr>
</table>
<br/>

<%= link_to trn_geth('BUTTON_ADD'), new_door_panel_family_door_panel_path(@door_panel_family) %> |
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_panel_families_path %>

<table cellspacing="0">
  <tr class="header">
    <th><%= trn_geth('HEADER_NAME') %></th>
    <th><%= trn_geth('HEADER_PREVIEW') %></th>
    <th></th>
  </tr>
<% for door_panel in @door_panel_family.door_panels %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= door_panel.name %></td>
    <td>
      <%= image_tag 'door_panels/' + door_panel.preview_image_name unless door_panel.preview_image_name.blank? %>
    </td>
    <td>
      <%= link_to trn_geth('BUTTON_EDIT'), edit_door_panel_family_door_panel_path(@door_panel_family, door_panel) %> |
      <%= link_to trn_geth('BUTTON_DIMENSIONS'), door_panel_family_door_panel_door_panel_dimensions_path(@door_panel_family, door_panel) %> |
      <%= link_to trn_geth('BUTTON_DELETE'), door_panel_family_door_panel_path(@door_panel_family, door_panel), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/door_panels/new.html.erb
<h2><%= trn_get('TITLE_DOOR_PANEL_ADD') %></h2>

<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DOOR_PANEL_FAMILY') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= @door_panel_family.name %></td>
  </tr>
</table>
<br/>

<%= form_for [@door_panel_family, @door_panel], :method => :post do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag trn_geth('BUTTON_ADD') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_panel_family_door_panels_path(@door_panel_family) %>